services:
  muquem_v3_backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: general/php-8.3
    container_name: muquem_v3_app
    volumes:
      - .:/var/www/html
    ports:
      - "7500:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - muquem_v3_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  muquem_v3_network:
    driver: bridge
